drop table wo_accounts_receivable;
drop table wo_accounts_receivable_details;
drop table invoice_temp;
drop table wo_invoice;
drop table wo_invoice_comments;
drop table wo_invoice_creditnotes;
drop table wo_invoice_workorder;
drop table wo_tax;
drop table wo_charge;
drop table franchise;
drop table franchise_carriers;
drop table franchise_markup;
drop table role;
drop table user_restrictions;
drop table authorities;
drop table customer_markup;
drop table customer_markup_bak;
drop table franchise_markup;
drop table aaps_origin_city_mapping;
drop table aaps_rates_region_mapping_intermodal;
drop table aaps_rates_region_mapping_standard;
drop table apex_origin_city_mapping;
drop table apex_rates_region_mapping;
drop table blocked_polaris_us_rating_zone;
drop table canadapost_airstage_offices;
drop table canadapost_domestic_exp_rates;
drop table canadapost_domestic_fsalist;
drop table canadapost_domestic_pc_rates;
drop table canadapost_domestic_ratecoder;
drop table canadapost_domestic_reg_rates;
drop table canadapost_domestic_xp_rates;
drop table canadapost_international_air_parcel;
drop table canadapost_international_ratecoder;
drop table canadapost_international_surface;
drop table canadapost_international_xpresspost;
drop table canadapost_usa_expedited_parcel;
drop table canadapost_usa_ratecoder;
drop table canadapost_usa_xpresspost;
drop table cct_origin_city_mapping;
drop table cct_rates_region_mapping;
drop table cct_rates_region_mapping_expedited;
drop table cct_rates_region_mapping_intermodal;
drop table cctransaction;
drop table dhl_rate_transit_time;
drop table dhl_rates;
drop table dhl_zip_zone_mapping;
drop table frontline_postal_region_mapping;
drop table frontline_region_rates_mapping;
drop table fuel_surcharge;
drop table gojit_10lb_rates;
drop table gojit_15lb_rates;
drop table gojit_dc_areas;
drop table gojit_postalcode_zone_mapping;
drop table gojit_zone_city_rates_mapping;
drop table gojit_zoating_zone;
drop table polaris_city_postal_code_mapping;
drop table polaris_rates_mapping;
drop table polaris_rates_region_mapping;
drop table polaris_region_city_mapping;
drop table polaris_us_rating_zone;
drop table puro_freight_10lb_rates;
drop table puro_freight_15lb_rates;
drop table puro_freight_fsa;
drop table purolator_beyond_tariff;
drop table purolator_dangerous_goods;
drop table purolator_first_tariff_tariff_data;
drop table purolator_pins;
drop table purolator_province;
drop table purolator_service_point;
drop table purolator_special_conditions;
drop table purolator_surcharge_data;
drop table purolator_tariff_data;
drop table purolator_transit;
drop table purolator_unicode;
drop table speedy_10lb_rates;
drop table speedy_15lb_rates;
drop table speedy_postal_code_zone_mapping;
drop table surcharge_type;
drop table tst_domestic_base_code;
drop table tst_domestic_base_rate;
drop table tst_domestic_major_points;
drop table tst_domestic_rate;
drop table ups_acc_charges_can;
drop table ups_acc_charges_us;
drop table ups_das_zips_us;
drop table vitran_domestic_point;
drop table vitran_domestic_rate;
drop table vitran_domestic_transit;
drop table vitran_international_rate;
drop table vitran_international_transit;
drop table wce_origin_city_mapping;
drop table wce_rates_region_mapping;
drop table wo_subservice_eshipper_charge;
drop table canpar_manifest_details;
drop table cts_acc_charges;


alter table `user` drop `franchise_id`;
alter table `surcharge` drop `franchise_id`;
alter table `shipping_order_archive` drop `franchise_id`;
alter table `shipping_order_archive` drop `franchise_markup`;
alter table `service` drop `franchise_id`;
alter table `rt_zone_postal_code` drop `franchise_id`;
alter table `rt_zone_city_map` drop `franchise_id`;
alter table `rt_zone` drop `franchise_id`;
alter table `rt_vehicle_type` drop `franchise_id`;
alter table `rt_transit_code_vehicle_rate` drop `franchise_id`;
alter table `rt_service_transit_code_rate` drop `franchise_id`;
alter table `rt_rate` drop `franchise_id`;
alter table `rt_charge_type` drop `franchise_id`;
alter table `pins` drop `franchise_id`;
alter table `package_type` drop `franchise_id`;
alter table `order_subservice_eshipper_charge` drop `franchise_id`;
alter table `order_service` drop `franchise_id`;
alter table `order_edi_header` drop `franchise_id`;
alter table `order_agent` drop `franchise_id`;
alter table `order_accounts_receivable` drop `franchise_id`;
alter table `order_accounts_payable_transactions` drop `franchise_id`;
alter table `order_accounts_payable_payables` drop `franchise_id`;
alter table `order_accounts_payable_category` drop `franchise_id`;
alter table `news` drop `franchise_id`;
alter table `merchant_account` drop `franchise_id`;
alter table `logged_event` drop `franchise_id`;
alter table `invoice` drop `franchise_id`;
alter table `employee` drop `franchise_id`;
alter table `customs_invoice` drop `franchise_id`;
alter table `customer_order` drop `franchise_id`;
alter table `customer_order` drop `franchise_markup`;
alter table `customer` drop `franchise_id`;
alter table `cod_account` drop `franchise_id`;
alter table `agent` drop `franchise_id`;



alter table customer add activated_at DATETIME;

update customer set activated_at = created_at where active;

alter table customer drop `active`;




update customer_order set selected_quote_id=null where exists (select service_id from selected_quote SQ where SQ.id=customer_order.selected_quote_id and SQ.service_id = 0 or SQ.service_id is null);

update customer_order set selected_quote_id = null where not exists (select * from selected_quote where id=customer_order.selected_quote_id);
