#!/bin/bash

HOST="$1"
x=`mktemp`
login=${2}

trap "echo -e '\\n\\nEXITING\\n'; rm -f ${x}" EXIT
trap "echo UNEXPECTED ERROR; rm ${x}; exit " ERR

sess='set-password'

http --check-status --session=$sess -f POST $HOST:8080/api/login username=admin password="${FREIGHTCOM_admin}"
echo SSSS $?

http --check-status -pb --session=$sess http://${HOST}:8080/api/user/search/findByLogin "name==${login}" > $x

id=`php json_extract.php $x '_embedded.user.0.resourceId'`
echo "ID IS '$id'"

http --check-status --session=$sess --json -f POST http://${HOST}:8080/api/user/resetPassword/$id


