#!/bin/bash

if [ $# -lt 3 ]; then
  echo "usage: `basename "${0}"` user-name password host"
  exit
fi

HOST="$3"
x=`mktemp`
login=${1}
dir=`dirname "$0"`

trap "echo -e '\\n\\nEXITING\\n'; rm -f ${x}" EXIT
trap "echo UNEXPECTED ERROR; rm ${x}; exit " ERR

sess='set-password'

http --check-status --session=$sess -f POST $HOST:8080/api/login username=admin password="${FREIGHTCOM_admin}"

echo "Looking up ${login}"

http --check-status -pb --session=$sess http://${HOST}:8080/api/user/search/findByLogin "name==${login}" > $x


id=`php "${dir}/json_extract.php" $x '_embedded.user.0.resourceId'`
echo "ID IS '$id'"

http --check-status --session=$sess --json -f PUT http://${HOST}:8080/api/user/$id password="${2}"

http --check-status --session=$sess -f POST $HOST:8080/api/logout

http --check-status -pHBhb --session=$sess -f POST $HOST:8080/api/login "username=$login" "password=${2}"

