#!/bin/sh

HOST="$3"
x=`mktemp`
sess='set-password'

http --session=$sess -f POST $HOST:8080/api/login username=admin password="${FREIGHTCOM_admin}"

http -pb --session=$sess http://${HOST}:8080/api/user/${1} > $x

http -pb --session=$sess http://${HOST}:8080/api/user/${1} > $x

login=`php json_extract.php $x 'login'`
echo "LOGIN IS '$login'"

http --session=$sess --json -f PUT http://${HOST}:8080/api/user/${1} password="${2}"



http --session=$sess -f POST $HOST:8080/api/logout

http -pHBhb --session=$sess -f POST $HOST:8080/api/login "username=$login" "password=${2}"

rm $x
