#!/bin/bash

# Send a git request to backend first logging in as admin
# E.g.  ~/systems/spring-projects/project1/src/test/resources/test-route 162.242.163.68 /api/user/search/findByLogin?name=admin

if [ $# -lt 2 ]; then
  echo "usage: `basename "${0}"` host route [...args]"
  exit
fi

HOST=$1
route=${2:-/api}

shift
shift

echo RUNNING
echo $HOST $route

x=`mktemp`

trap "echo -e '\\n\\nEXITING\\n'; rm -f ${x}" EXIT
trap "echo UNEXPECTED ERROR; rm ${x}; exit " ERR

sess='mock1'

http --check-status --session=$sess -f POST $HOST/api/login username=admin password="${FREIGHTCOM_admin}"

http --check-status --session=$sess -f POST $HOST/api/set-session-role/1


http --check-status -pHBb --pretty=format --session=$sess "http://${HOST}${route}" $@



